// Code generated by go-swagger; DO NOT EDIT.

// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
// 	http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// BalloonStartCmd Command used to start a free page hinting run.
//
// swagger:model BalloonStartCmd
type BalloonStartCmd struct {

	// If Firecracker should automatically acknowledge when the guest submits a done cmd.
	AcknowledgeOnStop bool `json:"acknowledge_on_stop,omitempty"`
}

// Validate validates this balloon start cmd
func (m *BalloonStartCmd) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this balloon start cmd based on context it is used
func (m *BalloonStartCmd) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *BalloonStartCmd) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BalloonStartCmd) UnmarshalBinary(b []byte) error {
	var res BalloonStartCmd
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
