// Code generated by go-swagger; DO NOT EDIT.

// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
// 	http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SharedMemoryConfiguration Defines a shared memory region for host-guest communication.
//
// swagger:model SharedMemoryConfiguration
type SharedMemoryConfiguration struct {

	// Optional guest physical address for the shared memory region. If not specified, it will be auto-assigned.
	GuestAddr int64 `json:"guest_addr,omitempty"`

	// Path to the shared memory file on the host.
	// Required: true
	Path *string `json:"path"`

	// Size of shared memory in MiB.
	// Required: true
	// Minimum: 1
	SizeMib *int64 `json:"size_mib"`
}

// Validate validates this shared memory configuration
func (m *SharedMemoryConfiguration) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePath(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSizeMib(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SharedMemoryConfiguration) validatePath(formats strfmt.Registry) error {

	if err := validate.Required("path", "body", m.Path); err != nil {
		return err
	}

	return nil
}

func (m *SharedMemoryConfiguration) validateSizeMib(formats strfmt.Registry) error {

	if err := validate.Required("size_mib", "body", m.SizeMib); err != nil {
		return err
	}

	if err := validate.MinimumInt("size_mib", "body", *m.SizeMib, 1, false); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this shared memory configuration based on context it is used
func (m *SharedMemoryConfiguration) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SharedMemoryConfiguration) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SharedMemoryConfiguration) UnmarshalBinary(b []byte) error {
	var res SharedMemoryConfiguration
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
