// Code generated by go-swagger; DO NOT EDIT.

// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
// 	http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/firecracker-microvm/firecracker-go-sdk/client/models"
)

// PutNexusByIDReader is a Reader for the PutNexusByID structure.
type PutNexusByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutNexusByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 204:
		result := NewPutNexusByIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPutNexusByIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewPutNexusByIDDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPutNexusByIDNoContent creates a PutNexusByIDNoContent with default headers values
func NewPutNexusByIDNoContent() *PutNexusByIDNoContent {
	return &PutNexusByIDNoContent{}
}

/*
PutNexusByIDNoContent describes a response with status code 204, with default header values.

Nexus device is created/updated
*/
type PutNexusByIDNoContent struct {
}

// IsSuccess returns true when this put nexus by Id no content response has a 2xx status code
func (o *PutNexusByIDNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this put nexus by Id no content response has a 3xx status code
func (o *PutNexusByIDNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put nexus by Id no content response has a 4xx status code
func (o *PutNexusByIDNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this put nexus by Id no content response has a 5xx status code
func (o *PutNexusByIDNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this put nexus by Id no content response a status code equal to that given
func (o *PutNexusByIDNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the put nexus by Id no content response
func (o *PutNexusByIDNoContent) Code() int {
	return 204
}

func (o *PutNexusByIDNoContent) Error() string {
	return fmt.Sprintf("[PUT /nexus/{id}][%d] putNexusByIdNoContent", 204)
}

func (o *PutNexusByIDNoContent) String() string {
	return fmt.Sprintf("[PUT /nexus/{id}][%d] putNexusByIdNoContent", 204)
}

func (o *PutNexusByIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPutNexusByIDBadRequest creates a PutNexusByIDBadRequest with default headers values
func NewPutNexusByIDBadRequest() *PutNexusByIDBadRequest {
	return &PutNexusByIDBadRequest{}
}

/*
PutNexusByIDBadRequest describes a response with status code 400, with default header values.

Nexus device cannot be created/updated due to bad input
*/
type PutNexusByIDBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this put nexus by Id bad request response has a 2xx status code
func (o *PutNexusByIDBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this put nexus by Id bad request response has a 3xx status code
func (o *PutNexusByIDBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put nexus by Id bad request response has a 4xx status code
func (o *PutNexusByIDBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this put nexus by Id bad request response has a 5xx status code
func (o *PutNexusByIDBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this put nexus by Id bad request response a status code equal to that given
func (o *PutNexusByIDBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the put nexus by Id bad request response
func (o *PutNexusByIDBadRequest) Code() int {
	return 400
}

func (o *PutNexusByIDBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /nexus/{id}][%d] putNexusByIdBadRequest %s", 400, payload)
}

func (o *PutNexusByIDBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /nexus/{id}][%d] putNexusByIdBadRequest %s", 400, payload)
}

func (o *PutNexusByIDBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *PutNexusByIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPutNexusByIDDefault creates a PutNexusByIDDefault with default headers values
func NewPutNexusByIDDefault(code int) *PutNexusByIDDefault {
	return &PutNexusByIDDefault{
		_statusCode: code,
	}
}

/*
PutNexusByIDDefault describes a response with status code -1, with default header values.

Internal server error.
*/
type PutNexusByIDDefault struct {
	_statusCode int

	Payload *models.Error
}

// IsSuccess returns true when this put nexus by ID default response has a 2xx status code
func (o *PutNexusByIDDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this put nexus by ID default response has a 3xx status code
func (o *PutNexusByIDDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this put nexus by ID default response has a 4xx status code
func (o *PutNexusByIDDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this put nexus by ID default response has a 5xx status code
func (o *PutNexusByIDDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this put nexus by ID default response a status code equal to that given
func (o *PutNexusByIDDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the put nexus by ID default response
func (o *PutNexusByIDDefault) Code() int {
	return o._statusCode
}

func (o *PutNexusByIDDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /nexus/{id}][%d] putNexusByID default %s", o._statusCode, payload)
}

func (o *PutNexusByIDDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /nexus/{id}][%d] putNexusByID default %s", o._statusCode, payload)
}

func (o *PutNexusByIDDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *PutNexusByIDDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
