// Code generated by go-swagger; DO NOT EDIT.

// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
// 	http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/firecracker-microvm/firecracker-go-sdk/client/models"
)

// NewPutNexusByIDParams creates a new PutNexusByIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutNexusByIDParams() *PutNexusByIDParams {
	return &PutNexusByIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutNexusByIDParamsWithTimeout creates a new PutNexusByIDParams object
// with the ability to set a timeout on a request.
func NewPutNexusByIDParamsWithTimeout(timeout time.Duration) *PutNexusByIDParams {
	return &PutNexusByIDParams{
		timeout: timeout,
	}
}

// NewPutNexusByIDParamsWithContext creates a new PutNexusByIDParams object
// with the ability to set a context for a request.
func NewPutNexusByIDParamsWithContext(ctx context.Context) *PutNexusByIDParams {
	return &PutNexusByIDParams{
		Context: ctx,
	}
}

// NewPutNexusByIDParamsWithHTTPClient creates a new PutNexusByIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutNexusByIDParamsWithHTTPClient(client *http.Client) *PutNexusByIDParams {
	return &PutNexusByIDParams{
		HTTPClient: client,
	}
}

/*
PutNexusByIDParams contains all the parameters to send to the API endpoint

	for the put nexus by ID operation.

	Typically these are written to a http.Request.
*/
type PutNexusByIDParams struct {

	/* Body.

	   Nexus device properties
	*/
	Body *models.Nexus

	/* ID.

	   The id of the nexus device
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put nexus by ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutNexusByIDParams) WithDefaults() *PutNexusByIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put nexus by ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutNexusByIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put nexus by ID params
func (o *PutNexusByIDParams) WithTimeout(timeout time.Duration) *PutNexusByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put nexus by ID params
func (o *PutNexusByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put nexus by ID params
func (o *PutNexusByIDParams) WithContext(ctx context.Context) *PutNexusByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put nexus by ID params
func (o *PutNexusByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put nexus by ID params
func (o *PutNexusByIDParams) WithHTTPClient(client *http.Client) *PutNexusByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put nexus by ID params
func (o *PutNexusByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the put nexus by ID params
func (o *PutNexusByIDParams) WithBody(body *models.Nexus) *PutNexusByIDParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the put nexus by ID params
func (o *PutNexusByIDParams) SetBody(body *models.Nexus) {
	o.Body = body
}

// WithID adds the id to the put nexus by ID params
func (o *PutNexusByIDParams) WithID(id string) *PutNexusByIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the put nexus by ID params
func (o *PutNexusByIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PutNexusByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
